export const mockProducts = [
  {
    id: '1',
    name: 'Premium Basmati Rice',
    category: 'Grains',
    originCountry: 'India',
    flag: '🇮🇳',
    description: 'Extra long grain Basmati rice known for its fragrance and delicate flavor.',
    price: 1250,
    unit: 'Per Metric Ton',
    moq: 10,
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80'],
    specs: { moisture: '12% Max', packing: '50kg PP Bags', shelfLife: '24 Months' },
    stock: 500,
  },
  {
    id: '2',
    name: 'Organic Black Pepper',
    category: 'Spices',
    originCountry: 'Vietnam',
    flag: '🇻🇳',
    description: 'High pungency organic black pepper corns, sun-dried to perfection.',
    price: 4500,
    unit: 'Per Metric Ton',
    moq: 5,
    images: ['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80'],
    specs: { moisture: '11% Max', packing: '25kg Paper Bags', shelfLife: '36 Months' },
    stock: 200,
  },
  {
    id: '3',
    name: 'Red Lentils (Masoor Dal)',
    category: 'Pulses',
    originCountry: 'Canada',
    flag: '🇨🇦',
    description: 'Split red lentils, rich in protein and fast cooking.',
    price: 850,
    unit: 'Per Metric Ton',
    moq: 20,
    images: ['https://images.unsplash.com/photo-1582294101967-16010b9915aa?auto=format&fit=crop&w=600&q=80'],
    specs: { moisture: '10% Max', packing: '50kg Jute Bags', shelfLife: '12 Months' },
    stock: 1000,
  },
  {
    id: '4',
    name: 'Fresh Cavendish Bananas',
    category: 'Fruits',
    originCountry: 'Ecuador',
    flag: '🇪🇨',
    description: 'Premium quality green cavendish bananas ready for export.',
    price: 450,
    unit: 'Per Metric Ton',
    moq: 15,
    images: ['https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=600&q=80'],
    specs: { moisture: 'N/A', packing: '18kg Carton Boxes', shelfLife: '45 Days' },
    stock: 800,
  },
  {
    id: '5',
    name: 'Yellow Onion',
    category: 'Vegetables',
    originCountry: 'Egypt',
    flag: '🇪🇬',
    description: 'Firm and pungent yellow onions with golden skin.',
    price: 320,
    unit: 'Per Metric Ton',
    moq: 20,
    images: ['https://images.unsplash.com/photo-1566385101042-1a0aa0c1268c?auto=format&fit=crop&w=600&q=80'],
    specs: { moisture: 'N/A', packing: '25kg Mesh Bags', shelfLife: '6 Months' },
    stock: 1500,
  },
  {
    id: '6',
    name: 'Soybeans',
    category: 'Oilseeds',
    originCountry: 'Brazil',
    flag: '🇧🇷',
    description: 'Non-GMO soybeans suitable for crushing and food products.',
    price: 520,
    unit: 'Per Metric Ton',
    moq: 50,
    images: ['https://images.unsplash.com/photo-1606085183492-3bc17e8893fb?auto=format&fit=crop&w=600&q=80'],
    specs: { moisture: '13% Max', packing: 'Bulk in Containers', shelfLife: '24 Months' },
    stock: 5000,
  }
];
